# Generated by Django 4.1.5 on 2023-05-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='static/theme'),
            preserve_default=False,
        ),
    ]
