# Generated by Django 4.1.5 on 2023-05-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
