# Generated by Django 4.1.5 on 2023-06-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='month',
            field=models.CharField(choices=[('general', 'general'), ('festival', 'festival'), ('happy birthday', 'happy birthday'), ('invitation', 'invitation')], default='general', max_length=50),
        ),
    ]
