# Generated by Django 4.1.5 on 2023-06-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_theme_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='month',
            new_name='category',
        ),
    ]
